services:
  llm-mock-server:
    container_name: llm-mock-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: curl localhost:8080 || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s
