test_cases:
  - test_case: user tries to use abstract values
    steps:
      - user: send money
        assertions:
          - bot_uttered:
              utter_name: utter_ask_transfer_money_recipient
      # the llm is extracting "good friend" as the recipient
      - user: to a good friend
        assertions:
          - slot_was_not_set:
              - name: transfer_money_recipient
          - bot_uttered:
              utter_name: utter_ask_transfer_money_recipient
      - user: okay, to Mary
        assertions:
          - slot_was_set:
              - name: transfer_money_recipient
                value: Mary
          - bot_uttered:
              utter_name: utter_ask_transfer_money_amount_of_money
      - user: "50"
        assertions:
          - slot_was_set:
              - name: transfer_money_amount_of_money
                value: "50"
          - bot_uttered:
              utter_name: utter_ask_transfer_money_final_confirmation
      - user: "yes"
        assertions:
          - bot_uttered:
              utter_name: utter_transfer_complete
